blank_issues_enabled: false
issue_templates:
  - name: "Bug Report"
    description: "Report a bug."
    title: "[Bug]: "
    labels: ["bug"]
    body: "./ISSUE_TEMPLATE/bug_report.md"
  - name: "Feature Request"
    description: "Propose a new feature or improvement."
    title: "[Feature]: "
    labels: ["enhancement"]
    body: "./ISSUE_TEMPLATE/feature_request.md"
  - name: "Documentation"
    description: "Suggest updates or additions to the documentation."
    title: "[Docs]: "
    labels: ["documentation"]
    body: "./ISSUE_TEMPLATE/documentation.md"
  - name: "General Report"
    description: "Provide general feedback or inquiries."
    title: "[General]: "
    labels: ["general"]
    body: "./ISSUE_TEMPLATE/general_report.md"
